const players = [
  {
    name: "Dimas Galih",
    number: "16",
    position: "Goalkeeper",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Fajar Setya",
    number: "71",
    position: "Goalkeeper",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Junaidi Bachtiar",
    number: "47",
    position: "Goalkeeper",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Ante Bakmaz",
    number: "5",
    position: "Defender",
    nation: "Australia",
    photo: "",
  },
  {
    name: "Jefferson Oliveira",
    number: "29",
    position: "Defender",
    nation: "Brazil",
    photo: "",
  },
  {
    name: "Andri Ibo",
    number: "28",
    position: "Defender",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Munhar",
    number: "20",
    position: "Defender",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Dany Saputra",
    number: "3",
    position: "Defender",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Ibrahim Sanjaya",
    number: "2",
    position: "Defender",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Yusuf Meilana",
    number: "31",
    position: "Defender",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Arif Setyawan",
    number: "42",
    position: "Defender",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Vava Mario Yagalo",
    number: "8",
    position: "Defender",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Galih Akbar",
    number: "93",
    position: "Midfielder",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Adi Eko Jayanto",
    number: "11",
    position: "Midfielder",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Eka Prasetya",
    number: "45",
    position: "Midfielder",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Bayu Otto",
    number: "6",
    position: "Midfielder",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Reksa Maulana",
    number: "19",
    position: "Midfielder",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Paolo Sitanggang",
    number: "70",
    position: "Midfielder",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Faris Aditama",
    number: "13",
    position: "Midfielder",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Sackie Teah Doe",
    number: "4",
    position: "Midfielder",
    nation: "Liberia",
    photo: "",
  },
  {
    name: "Gaspar Vega",
    number: "32",
    position: "Midfielder",
    nation: "Argentina",
    photo: "",
  },
  {
    name: "Zamorano",
    number: "21",
    position: "Midfielder",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Septian Bagaskara",
    number: "10",
    position: "Forward",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Antony Nugroho",
    number: "17",
    position: "Forward",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Ronaldo Wanma",
    number: "27",
    position: "Forward",
    nation: "Indonesia",
    photo: "",
  },
  {
    name: "Nikola Asceric",
    number: "14",
    position: "Forward",
    nation: "Serbia",
    photo: "",
  },
  // {
  // 	name: "",
  // 	// number: "",
  // 	position: "",
  // 	nation: "",
  // 	photo: ""
  // },
  // {
  // 	name: "",
  // 	// number: "",
  // 	position: "",
  // 	nation: "",
  // 	photo: ""
  // },
  // {
  // 	name: "",
  // 	// number: "",
  // 	position: "",
  // 	nation: "",
  // 	photo: ""
  // },
];

export default players;
